# -*- coding: utf-8 -*-
"""pysdr_uk_doa_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bk9mxS4K3pGU7ZzsVLRgz7kirP6XUGTU
"""

import numpy as np

A = np.random.randn(3,10) # 3x10
B = np.arange(10) # 1D array of length 10
B = B.reshape(-1,1) # 10x1
C = A @ B # matrix multiply
print(C.shape) # 3x1
C = C.squeeze() # дивись наступну підсекцію
print(C.shape) # 1D масив з довжиною 3, легше для виводу і іншого коду Python, що не пов'язаний з обробкою матриць

A,B,C